export const compliments = [
  "Your smile is contagious.",
  "I bet you make babies smile.",
  "You have the best laugh.",
  "You light up the room.",
  "You have a great sense of humor.",
  "If cartoon bluebirds were real, a couple of 'em would be sitting on your shoulders singing right now.",
  "You're like sunshine on a rainy day.",
  "You bring out the best in other people.",
  "I bet you sweat glitter.",
  "Colors seem brighter when you're around.",
  "You're more fun than a ball pit filled with candy.",
  "Jokes are funnier when you tell them.",
  "You always know how to find that silver lining.",
  "You're a candle in the darkness.",
  "Being around you is like a happy little vacation.",
  "You're more fun than bubble wrap.",
  "You're like a breath of fresh air.",
  "You're someone's reason to smile.",
  "How do you keep being so funny and making everyone laugh?",
  "I appreciate you.",
  "You are the most perfect you there is.",
  "You are enough.",
  "You're all that and a super-size bag of chips.",
  "On a scale from 1 to 10, you're an 11.",
  "You've got all the right moves.",
  "Everything would be better if more people were like you.",
  "When you're not afraid to be yourself, that's when you're incredible.",
  "You're wonderful.",
  "You're better than a triple-scoop ice cream cone. With sprinkles.",
  "You're one of a kind.",
  "If you were a box of crayons, you'd be the big industrial name-brand one with a built-in sharpener.",
  "Who raised you? They deserve a medal for a job well done.",
  "Somehow you make time stop and fly all at the same time.",
  "In high school, I bet you were voted \"most likely to continue being awesome\".",
  "If you were a scented candle they'd have to call it Perfectly Imperfect (and it would smell like summer).",
  "There's ordinary, and then there's you.",
  "You're even better than a unicorn because you're real.",
  "You're really something special.",
  "You are beautiful, I am beautiful, let's be beautiful together"
];
